from __future__ import annotations

import argparse
from pathlib import Path


SOURCE_COLUMNS = 80
SOURCE_ROWS = 25
TARGET_COLUMNS = 80
TARGET_ROWS = 25
FRAME_RECORD_SIZE = 256
FRAME_RECORD_COUNT = 8
FRAME_BYTE_SIZE = FRAME_RECORD_SIZE * FRAME_RECORD_COUNT
FRAME_PADDING_BYTES = FRAME_BYTE_SIZE - (TARGET_COLUMNS * TARGET_ROWS)
FIRST_FRAME_ALIGNMENT_BYTES = FRAME_RECORD_SIZE
FRAME_RECORD_SHIFT = 3


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Crop Bad Apple ASCII frames and pack them into an OBJ trailer payload for badapple.cas."
    )
    parser.add_argument(
        "--frames-dir",
        type=Path,
        default=Path("frames-ascii"),
        help="Directory containing source ASCII frame files.",
    )
    parser.add_argument(
        "--payload-out",
        type=Path,
        default=Path("badapple-frames.bin"),
        help="Output binary payload path.",
    )
    parser.add_argument(
        "--include-out",
        type=Path,
        default=Path("badapple-frames.inc"),
        help="Output CAS include path.",
    )
    parser.add_argument(
        "--frame-step",
        type=int,
        default=2,
        help="Take every Nth source frame.",
    )
    return parser.parse_args()


def read_frame(frame_path: Path) -> list[str]:
    lines = frame_path.read_text(encoding="ascii").splitlines()
    if len(lines) != SOURCE_ROWS:
        raise ValueError(f"{frame_path} has {len(lines)} rows; expected {SOURCE_ROWS}.")

    for index, line in enumerate(lines, start=1):
        if len(line) != SOURCE_COLUMNS:
            raise ValueError(
                f"{frame_path} row {index} has {len(line)} columns; expected {SOURCE_COLUMNS}."
            )

    return lines


def crop_frame(lines: list[str]) -> bytes:
    top = (SOURCE_ROWS - TARGET_ROWS) // 2
    left = (SOURCE_COLUMNS - TARGET_COLUMNS) // 2
    cropped_rows = [line[left:left + TARGET_COLUMNS] for line in lines[top:top + TARGET_ROWS]]
    frame_bytes = "".join(cropped_rows).encode("ascii")
    if len(frame_bytes) != TARGET_COLUMNS * TARGET_ROWS:
        raise ValueError("Internal error while cropping frame payload.")

    return frame_bytes + (b"\x00" * FRAME_PADDING_BYTES)


def emit_include(include_path: Path, payload_path: Path, frame_count: int) -> None:
    relative_payload = payload_path.name
    first_frame_record = FIRST_FRAME_ALIGNMENT_BYTES // FRAME_RECORD_SIZE
    include_text = "\n".join(
        [
            "; Generated by badapple/build_frames.py",
            f"FRAME_COUNT = {frame_count}",
            f"FRAME_COLUMNS = {TARGET_COLUMNS}",
            f"FRAME_ROWS = {TARGET_ROWS}",
            f"FRAME_RECORD_SIZE = {FRAME_RECORD_SIZE}",
            f"FRAME_RECORD_COUNT = {FRAME_RECORD_COUNT}",
            f"FRAME_RECORD_SHIFT = {FRAME_RECORD_SHIFT}",
            f"FRAME_BYTE_SIZE = {FRAME_BYTE_SIZE}",
            f"FRAME_LAST_INDEX = {frame_count - 1}",
            f"FRAME_DATA_START_RECORD = {first_frame_record}",
            f".objinclude FRAMES_DATA, \"{relative_payload}\"",
            "",
        ]
    )
    include_path.write_text(include_text, encoding="ascii")


def main() -> None:
    args = parse_args()

    if args.frame_step < 1:
        raise ValueError("--frame-step must be at least 1.")

    frames_dir = args.frames_dir.resolve()
    payload_out = args.payload_out.resolve()
    include_out = args.include_out.resolve()

    source_frames = sorted(frame for frame in frames_dir.iterdir() if frame.is_file())
    selected_frames = source_frames[::args.frame_step]
    if not selected_frames:
        raise ValueError("No frames selected.")

    payload_out.parent.mkdir(parents=True, exist_ok=True)
    include_out.parent.mkdir(parents=True, exist_ok=True)

    payload = bytearray(b"\x00" * FIRST_FRAME_ALIGNMENT_BYTES)
    for frame_path in selected_frames:
        payload.extend(crop_frame(read_frame(frame_path)))

    payload_out.write_bytes(payload)
    emit_include(include_out, payload_out, len(selected_frames))

    first_frame_record = FIRST_FRAME_ALIGNMENT_BYTES // FRAME_RECORD_SIZE

    print(f"frames={len(selected_frames)}")
    print(f"payload_bytes={len(payload)}")
    print(f"frame_bytes={FRAME_BYTE_SIZE}")
    print(f"frame_data_start_record={first_frame_record}")


if __name__ == "__main__":
    main()